//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace departmental_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Id { get; set; }
        public string Invoice_Id { get; set; }
        public string Date { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
        public string Address { get; set; }
    }
}
