//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace departmental_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Product_Id { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public string Description { get; set; }
        public string unit_price { get; set; }
        public string sell_price { get; set; }
        public string Quantity { get; set; }
        public string Sold { get; set; }
        public string type { get; set; }
        public string purchase_price { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string shop { get; set; }
        public string recieved_by { get; set; }
        public string brand { get; set; }
        public string supplier { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    }
}
