//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace departmental_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_products
    {
        public string Product_Id { get; set; }
        public string Product_name { get; set; }
        public string Product_Amount { get; set; }
        public string Product_Code { get; set; }
        public string Discount { get; set; }
        public string Product_Description { get; set; }
        public string Product_Price { get; set; }
        public string Quantity { get; set; }
        public string Unit { get; set; }
        public string Product_Invoice { get; set; }
    }
}
